### PR TITLE
Discrete value range slider should be shorter

### LINKED ISSUE #1002: [designspace panel] Discrete value range slider should be shorter
Currently, the range slider is as wide as there's space, but for a discrete value slider I think it should be shorter, depending on the number of values.

Current situation:

image

Desired layout:

image

(Sketch is not pixel-perfect)

When the number of values becomes to big that the slider would become to wide, it should be made to match the current behavior (fill the available space, bit not more).

### PR DESCRIPTION
**Pull request by fatih-erikli**
Fixes #1002

### CODE REVIEW

**Comment by justvanrossum** [comment]
The item spacing is too wide and not consistent:

image

Please make it match the sketch in #1002

**Comment by fatih-erikli** [comment]
This is a tricky css problem, I will come back to this later.

**Comment by fatih-erikli** [comment]
If you have a suggestion, I'd be happy to hear.

**Comment by justvanrossum** [comment]
The element could have its own css that depends on the number of values.

**Comment by fatih-erikli** [comment]
Can you elaborate? @justvanrossum

**Comment by justvanrossum** [comment]
Something like:
```js
    el = html.div({style: `width: ${some_computed_value_based_on_num_values}em;`);
```
or:
```js
    el.style = `width: ${some_computed_value_based_on_num_values}em;`;
```

**Comment by fatih-erikli** [comment]
`max-width: ${this.values.length * 20}px; width: 100%;`

This is how the total width calculated currently.

They look ok, however not pixel perfect.

Screenshot 2023-12-17 at 00 42 58

**Comment by fatih-erikli** [comment]
Not only the tickmarks, the builtin range slider has that gap too.

Screenshot 2023-12-17 at 00 48 08

Maybe thumb-width should be added to the calculation. I tried, it didn't help.

**Comment by justvanrossum** [comment]
I don't think you are accounting for the track length bore the first and after the last tickmark. I think the computation should be something like:
```js
this.values.length * 20 + margin * 2
```
Where `margin` is the space before the first chckmark.

**Comment by fatih-erikli** [comment]
Space before the checkmark is half of thumb width. I tried that, it doesn't help.

**Comment by fatih-erikli** [comment]
Assigning it to @justvanrossum for the remaining gap issue.

**Pull request merged**
