### PR TITLE
Modal dialog improvement

### LINKED ISSUE #1176: Modal dialog shows scroll bar
I think this is not intended
image

### PR DESCRIPTION
**Pull request by navv-1**
This pr will fix this issue,
image

and fix #1176

### CODE REVIEW

**Comment by justvanrossum** [comment]
This must be related to https://github.com/googlefonts/fontra/issues/1175 and https://github.com/googlefonts/fontra/pull/1180/files, and I had an uneasy feeling about the fix.

I have an uneasy feeling about the fix in this PR, too: I don't think `max-height: 32em;` is what we want: it should be able to get as big as possible, with some space above and below. 

Indeed, I just tested: try "Add Component", this should show a big list, and it should be as big as possible (within roughly the 80vh).

**Comment by navv-1** [comment]
Actually, we can also remove the max-height and let it overflow since we have the scrollbar on the edge
image

**Comment by justvanrossum** [comment]
Hmm,  we shouldn't have that scrollbar at the edge. The dialog should fit on the page (with some margin above and below), and any scrolling should be handled by its contents.

Your original problem is that we get too many scrollbars when the window isn't tall enough, right?

**Comment by justvanrossum** [comment]
Can you compare how the situation was before https://github.com/googlefonts/fontra/pull/1146? I feel that PR had larger consequences than intended.

**Comment by navv-1** [comment]
Look at the add and remove button, if we use vh we will get this result when the window isn't tall enough
image

**Comment by justvanrossum** [comment]
So what I'm asking is, did that issue exist before #1146 was merged?

**Comment by navv-1** [comment]
this is after #1145 merged
image
image

**Comment by justvanrossum** [comment]
Ok, so we need to back up more. Was it ok before #1145? Was it ever ok? I need to know whether this is a regression or something that was always broken.

**Comment by navv-1** [comment]
I tried after #929 merged and it's not different

**Comment by justvanrossum** [comment]
And before that one?

**Comment by navv-1** [comment]
Yes, even before the menu bar was merged. I think it's not regression.

**Comment by navv-1** [comment]
> Indeed, I just tested: try "Add Component", this should show a big list, and it should be as big as possible (within roughly the 80vh).

Instead of looking at a long list, I prefer to use the search bar and get a shorter list.

**Comment by justvanrossum** [comment]
> Instead of looking at a long list, I prefer to use the search bar and get a shorter list.

I disagree. I don't want a hardcoded maximum height for the dialog.

I feel that https://github.com/googlefonts/fontra/commit/e98e75c3728d6ba020ca5e3f45aed5d6231da5d9 / https://github.com/googlefonts/fontra/pull/1170 was wrong, and we should fix that problem in a different way.

**Comment by navv-1** [comment]
I just brought back the `max-height`. The only problem that I found is in the add and remove button. But this kind of situation maybe would never happen in the real world :D
image

**Comment by justvanrossum** [comment]
Thanks!

That might be related to the minHeight of the axis list:

https://github.com/googlefonts/fontra/blob/c6d24ef0f36e26aab86b1e43e08f372208447ba0/src/fontra/views/editor/panel-designspace-navigation.js#L965

**Comment by justvanrossum** [comment]
Changing that to "3em" seems to improve it.

**Comment by navv-1** [comment]
I changed that to 10vh and I think it's much better.

image

I also add `min-height: 10em` to the dialog box to prevent it from shrinking too short. It makes dialog a bit higher when it has a short message. I hope it's still acceptable.

image

**Comment by justvanrossum** [comment]
Hm, I'm not happy with the use of vh in the list minHeight. This should be an absolute value, and should not depend on the view height. You can tweak the exact value of 3em, but please use em.

Secondly, I am not happy with the taller dialog for short messages. If this is to make sure the dialog doesn't break for a very small window height: I'm actually ok with some breakage under such tight conditions. The app is not really meant for such small windows.

**Review by justvanrossum — APPROVED** [review]

**Comment by justvanrossum** [comment]
Thank you once again for your contributions! It's much appreciated.

**Pull request merged**
