### PR TITLE
fix: lock-button-tooltip #1768

### PR DESCRIPTION
**Pull request by giovanniTramonto**
+ handle `ui-form` overflow and padding on `:host` (to prevent clipping)
+ add form modifier class for `selection-info` and `selection-transformation` (keeps flex settings within parent element scope)

### CODE REVIEW

**Comment by ollimeier** [comment]
@justvanrossum I checke out the branch and tested it. I can confirm that it fixes the issue with the tooltip:

Screenshot 2024-12-16 at 20 55 11

**Comment by justvanrossum** [comment]
Does adding padding to `:host` have any downsides?

**Comment by ollimeier** [comment]
> Does adding padding to `:host` have any downsides?

I sadly don't have experiences with `:host`, but I don't read about any downsides. You can simply style `:host` as any other CSS class.
Please see: https://developer.mozilla.org/en-US/docs/Web/CSS/:host

The following might also be interesting to read: 
https://stackoverflow.com/questions/46448385/use-of-host-selector-vs-container-div#answer-46478233

I am wondering if this should be done in other places as well?

**Comment by justvanrossum** [comment]
My question wasn't about `:host`, but about adding the padding to the ui-info itself instead of where it is being used.

I'm curious if there is a difference in appearance before and after:
- with long axis names in the selection info panel
- the scroll bar of the selection info panel

**Comment by giovanniTramonto** [comment]
The branch fixes the clipping issue. But there is more. I’d propose a component `panel-section` that concerns the overflow and wraps any contents inside. It would allow multiple scrollable boxes in the panel. Then `overflow` does not need to be a part of `ui-form` anymore.

**Comment by ollimeier** [comment]
> My question wasn't about `:host`, but about adding the padding to the ui-info itself instead of where it is being used.
> 
> I'm curious if there is a difference in appearance before and after:
> 
> * with long axis names in the selection info panel
> * the scroll bar of the selection info panel

@justvanrossum I don't see any differences. Here are some screenshots in compare with our main branch:
Screenshot 2024-12-17 at 04 09 34
Screenshot 2024-12-17 at 04 08 59
Screenshot 2024-12-17 at 04 08 56
Screenshot 2024-12-17 at 04 09 37

**Comment by justvanrossum** [comment]
I don't think we should – at this time – go beyong fixing the issue at hand, though. This looks good, and I will play with it a bit, and then merge.

Btw. please sign that CLA thing....

**Review by justvanrossum — APPROVED** [review]

**Comment by giovanniTramonto** [comment]
> The branch fixes the clipping issue. But there is more. I’d propose a component `panel-section` that concerns the overflow and wraps any contents inside. It would allow multiple scrollable boxes in the panel. Then `overflow` does not need to be a part of `ui-form` anymore.

https://github.com/googlefonts/fontra/pull/1868

**Pull request merged**
