### PR TITLE
Replace raw "language code" with a popup

### LINKED ISSUE #746: [reference font] replace raw "language code" with a popup
The popup should show the superset of languages supported by the dropped fonts.

The Wakamaifondue Beta implements this nicely (probably with lib-font).

- https://wakamaifondue.com/beta/
- https://github.com/Wakamai-Fondue/

image

### PR DESCRIPTION
**Pull request by fatih-erikli**
Fixes #746.

### CODE REVIEW

**Comment by justvanrossum** [comment]
Where did you get the list from? It is probably not complete, right?

**Comment by fatih-erikli** [comment]
I googled BCP-47 language tags. Where should we get the exact list? @justvanrossum.

**Comment by justvanrossum** [comment]
Actually, the OpenType tag would be useful of we ever parse the language information from the actual fonts. Maybe we should just use [ot-to-html-lang.js](https://github.com/Wakamai-Fondue/wakamai-fondue-engine/blob/master/src/tools/ot-to-html-lang.js) as is.

(While parsing the font would be best, I'm worried about performance for big fonts.)

**Comment by fatih-erikli** [comment]
This is too much. I am not sure if `Anglo-Saxon` or `Berber` should be included in this list.

**Comment by fatih-erikli** [comment]
This list looks more realistic https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes

**Comment by fatih-erikli** [comment]
There is a language code list in googlefonts page
https://fonts.google.com/knowledge/using_type/language_support_in_fonts

Belarusian is missing that I notice

**Comment by fatih-erikli** [comment]
Maybe parsing the font could be done in Python side if we are worried about the performance.

**Comment by justvanrossum** [comment]
1. We need to set the `lang` attribute, so it _has_ to be BCP-47.
3. The list is not "too much", but we may need a search-like function. Perhaps `<select>` is the wrong UI for this. Unless we parse the fonts.
4. Please try to find out how wakamaifondue parses the language tags from fonts and converts them to human friendly names and BCP-47 codes. It likely uses lib-font, and I'd be curious to see how it can be used.
5. Reference-font is a client-side feature by design. Uploading to the server is not an option.

(I do worry about the inbalance between the effort of implementing this feature versus its (low) priority.)

**Comment by fatih-erikli** [comment]
I tried wakamaifoundue, it isn't working well. Try it with `GoogleSans`.

**Comment by fatih-erikli** [comment]
Wakamai fondue worked well with IBM Flex Sans font.

It returns these:
Afrikaans, Albanian, Azerbaijani, Basque, Belarusian, Bosnian, Bulgarian, Catalan, Croatian, Czech, Danish, Dutch, English, Estonian, Faroese, Filipino, Finnish, French, Galician, German, Greek, Hungarian, Icelandic, Indonesian, Irish, Italian, Kazakh, Latvian, Lithuanian, Macedonian, Malay, Mongolian, Norwegian Bokmål, Polish, Portuguese, Romanian, Russian, Serbian, Slovak, Slovenian, Spanish, Swahili, Swedish, Tongan, Turkish, Ukrainian, Uzbek, Vietnamese, Welsh, Zulu

I understood that you suggest lookup these language names in [ot-to-html-lang.js](https://github.com/Wakamai-Fondue/wakamai-fondue-engine/blob/master/src/tools/ot-to-html-lang.js) and get the html codes of them.

We can show them as 
- Select
- Textinput with datalist element [example](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist)
- Select with search input [example](https://react-select.com/)

**Comment by fatih-erikli** [comment]
The simplest solution looks like defining all the language codes in `ot-to-html-lang.js` as `datalist` element for the textinput.

**Comment by justvanrossum** [comment]
> I tried wakamaifoundue, it isn't working well.

Can you be more specific about what didn't work well?

**Comment by fatih-erikli** [comment]
It didn't work with the font I tried (Google Sans). Supported languages were empty in the result.

**Comment by justvanrossum** [comment]
> It didn't work with the font I tried

You tried it on the wakamaifondue beta site? It worked for me with the subset, but froze on the full font (I could perhaps have completed eventually, but I didn't have the patience.)

I'm pretty sure Wakamaifondue does a lot more font parsing than only getting the languages out, and I'd like to know how long it would take to do just that. Can you find the code in Wakamaifondue that is responsible for parsing the languages, and adapt it for a test we can do ourselves?

**Comment by fatih-erikli** [comment]
> You tried it on the wakamaifondue beta site?

Yes

>  Can you find the code in Wakamaifondue that is responsible for parsing the languages

It reads "GSUB" table of the binary font. Full file read is required.

https://github.com/Wakamai-Fondue/wakamai-fondue-engine/blob/master/src/fondue/Fondue.js#L964

In my opinion, full-binary read should be in one side, either in Python or Javascript.

**Comment by justvanrossum** [comment]
> > Can you find the code in Wakamaifondue that is responsible for parsing the languages

> It reads "GSUB" table of the binary font. Full file read is required.

> https://github.com/Wakamai-Fondue/wakamai-fondue-engine/blob/master/src/fondue/Fondue.js#L964

Ah great. Check also:

https://github.com/Wakamai-Fondue/wakamai-fondue-engine/blob/326729ffdbabefa3001b596391e16a906732481c/src/fondue/Fondue.js#L136-L138

> In my opinion, full-binary read should be in one side, either in Python or Javascript.

Like I said before, reference-font is a client-side feature, so JS it is.

I would love to know how long it takes for a big (GS) font to extract the languages in a browser.

**Comment by fatih-erikli** [comment]
I delete this PR, start a new one.

**Pull request closed without merging**
