### PR TITLE
Migrate server info to application settings

### LINKED ISSUE #1668: Migrate Server info to Application settings

### PR DESCRIPTION
**Pull request by ollimeier**
Fixes #1668

### CODE REVIEW

**Comment by justvanrossum** [comment]
Can you post a screenshot of that Fontra menu submenu? I’m away from my computer but would love to see.

**Comment by ollimeier** [comment]
> Can you post a screenshot of that Fontra menu submenu? I’m away from my computer but would love to see.

Sure:
Screenshot 2024-09-24 at 17 32 53

**Comment by justvanrossum** [comment]
This raises the question about how we handle the same situation under “Font”. 

We don’t have many items under Fontra, so perhaps this should be a flat list instead of a submenu.

**Comment by ollimeier** [comment]
> This raises the question about how we handle the same situation under “Font”.
> 
> We don’t have many items under Fontra, so perhaps this should be a flat list instead of a submenu.

Ok, I removed the submenu:

Screenshot 2024-09-25 at 08 55 39

**Pull request merged**
