### PR TITLE
new pen tool icon

### PR DESCRIPTION
**Pull request by GaetanBaehr**
Here is a new icon for the pen tool using a pencil
image

### CODE REVIEW

**Comment by justvanrossum** [comment]
If you could run `python icons/export-icons-as-svg.py` that would be great (it rebuilds the SVG icons from the .ufo)

**Comment by GaetanBaehr** [comment]
I ran it

**Comment by justvanrossum** [comment]
With this new design, I think we should rename the glyphs/svg files to:

- `pencil`
- `pencilquad`

(This would also be a change in the source code.)

**Comment by GaetanBaehr** [comment]
should I rename them?

**Comment by justvanrossum** [comment]
Let's leave it for now. I'll merge, and we can rename later if we want.

**Pull request merged**
