### PR TITLE
Fix: Tooltip in bottom position renders misaligned

### LINKED ISSUE #1119: Tooltip in `bottom` position renders misaligned
Mentioned in #1112.

### PR DESCRIPTION
**Pull request by fatih-erikli**
Fixes #1119.

### CODE REVIEW

**Comment by justvanrossum** [comment]
@ollimeier, can you manually verify that this change fixes the bottom alignment issue in https://github.com/googlefonts/fontra/pull/1112 (please don't commit there, just check, then throw away the change)

**Comment by fatih-erikli** [comment]
Feel free to merge my branch into yours if the fix looks ok, I set the target branch for yours.

**Comment by justvanrossum** [comment]
Ah I see, I missed that you targeted the branch for #1110.

**Comment by ollimeier** [comment]
@fatih-erikli Thank you very much.

**Pull request merged**
